#!/bin/bash

NAME=init-script-test
JAR_INSTALL_DIR=/usr/local/init-script-test
INIT_SCRIPT_INSTALL_DIR=/etc/init.d

rm -f $JAR_INSTALL_DIR/"$NAME"-standalone.jar
rm -f $INIT_SCRIPT_INSTALL_DIR/"$NAME"d